name: CheckDeployStaging
on:
  - deployment_status
  - workflow_dispatch

env:
  DEPLOY_URL: "https://dev3.atsign.wtf"

permissions:  # added using https://github.com/step-security/secure-workflows
  contents: read

jobs:
  audit:
    if: ${{ github.event_name == 'workflow_dispatch' || (github.event.deployment_status.state == 'success' && github.event.deployment_status.environment == 'gh-pages') }}
    runs-on: ubuntu-20.04
    steps:
      - name: Git checkout
        uses: actions/checkout@c85c95e3d7251135ab7dc9ce3241c5835cc595a9 # v3.5.3

      - uses: ./.github/workflows/LighthouseAudit
        with:
          url: ${{ env.DEPLOY_URL }}
