name: CI

on:
  push:
    branches:
      - trunk
  pull_request:
    branches:
      - trunk

permissions:  # added using https://github.com/step-security/secure-workflows
  contents: read

jobs:
  ci:
    strategy:
      matrix:
        command: ['build', 'build:staging']
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@b4ffde65f46336ab88eb53be808477a3936bae11 # v4.1.1
      - name: setup node
        uses: actions/setup-node@b39b52d1213e96004bfcb1c61a8a6fa8ab84f3e8 # v4.0.1
        with:
          node-version: '16'
      - name: clean install
        run: npm ci
      - name: ${{ matrix.command }}
        run: npm run ${{ matrix.command }}
      - name: ensure hugo_stats.json populated with > 100 lines
        run: |
          if [ $(wc -l < ./hugo_stats.json) -gt 100 ]; then
            echo "hugo_stats.json populated with > 100 lines"
          else
            echo "hugo_stats.json not populated with > 100 lines"
            exit 1
          fi