name: CI

on:
  push:
    branches:
      - trunk
  pull_request:
    branches:
      - trunk

permissions:  # added using https://github.com/step-security/secure-workflows
  contents: read

jobs:
  ci:
    strategy:
      matrix:
        command: ['build', 'build:staging']
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@c85c95e3d7251135ab7dc9ce3241c5835cc595a9 # v3.5.3
      - name: setup node
        uses: actions/setup-node@5e21ff4d9bc1a8cf6de233a3057d20ec6b3fb69d # v3.8.1
        with:
          node-version: '16'
      - name: clean install
        run: npm ci
      - name: ${{ matrix.command }}
        run: npm run ${{ matrix.command }}
      - name: ensure hugo_stats.json populated with > 100 lines
        run: |
          if [ $(wc -l < ./hugo_stats.json) -gt 100 ]; then
            echo "hugo_stats.json populated with > 100 lines"
          else
            echo "hugo_stats.json not populated with > 100 lines"
            exit 1
          fi